<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class RefSkill extends Model
{
    public $timestamps = false;
    protected $table = '_RefSkill';
    protected $fillable = [
        'Service', 'ID', 'GroupID', 'Basic_Code', 'Basic_Name', 'Basic_Group', 'Basic_Original', 'Basic_Level', 'Basic_Activity', 'Basic_ChainCode', 'Basic_RecycleCost', 'Action_PreparingTime', 'Action_CastingTime', 'Action_ActionDuration', 'Action_ReuseDelay', 'Action_CoolTime', 'Action_FlyingSpeed', 'Action_Interruptable', 'Action_Overlap', 'Action_AutoAttackType', 'Action_InTown', 'Action_Range', 'Target_Required', 'TargetType_Animal', 'TargetType_Land', 'TargetType_Building', 'TargetGroup_Self', 'TargetGroup_Ally', 'TargetGroup_Party', 'TargetGroup_Enemy_M', 'TargetGroup_Enemy_P', 'TargetGroup_Neutral', 'TargetGroup_DontCare', 'TargetEtc_SelectDeadBody', 'ReqCommon_Mastery1', 'ReqCommon_Mastery2', 'ReqCommon_MasteryLevel1', 'ReqCommon_MasteryLevel2', 'ReqCommon_Str', 'ReqCommon_Int', 'ReqLearn_Skill1', 'ReqLearn_Skill2', 'ReqLearn_Skill3', 'ReqLearn_SkillLevel1', 'ReqLearn_SkillLevel2', 'ReqLearn_SkillLevel3', 'ReqLearn_SP', 'ReqLearn_Race', 'Req_Restriction1', 'Req_Restriction2', 'ReqCast_Weapon1', 'ReqCast_Weapon2', 'Consume_HP', 'Consume_MP', 'Consume_HPRatio', 'Consume_MPRatio', 'Consume_WHAN', 'UI_SkillTab', 'UI_SkillPage', 'UI_SkillColumn', 'UI_SkillRow', 'UI_IconFile', 'UI_SkillName', 'UI_SkillToolTip', 'UI_SkillToolTip_Desc', 'UI_SkillStudy_Desc', 'AI_AttackChance', 'AI_SkillType', 'Param1', 'Param2', 'Param3', 'Param4', 'Param5', 'Param6', 'Param7', 'Param8', 'Param9', 'Param10', 'Param11', 'Param12', 'Param13', 'Param14', 'Param15', 'Param16', 'Param17', 'Param18', 'Param19', 'Param20', 'Param21', 'Param22', 'Param23', 'Param24', 'Param25', 'Param26', 'Param27', 'Param28', 'Param29', 'Param30', 'Param31', 'Param32', 'Param33', 'Param34', 'Param35', 'Param36', 'Param37', 'Param38', 'Param39', 'Param40', 'Param41', 'Param42', 'Param43', 'Param44', 'Param45', 'Param46', 'Param47', 'Param48', 'Param49', 'Param50'
    ];

    protected $casts = [
        'Service' => 'integer',
        'ID' => 'integer',
        'GroupID' => 'integer',
        'Basic_Original' => 'integer',
        'Basic_Level' => 'integer',
        'Basic_Activity' => 'integer',
        'Basic_ChainCode' => 'integer',
        'Basic_RecycleCost' => 'integer',
        'Action_PreparingTime' => 'integer',
        'Action_CastingTime' => 'integer',
        'Action_ActionDuration' => 'integer',
        'Action_ReuseDelay' => 'integer',
        'Action_CoolTime' => 'integer',
        'Action_FlyingSpeed' => 'integer',
        'Action_Interruptable' => 'integer',
        'Action_Overlap' => 'integer',
        'Action_AutoAttackType' => 'integer',
        'Action_InTown' => 'integer',
        'Action_Range' => 'integer',
        'Target_Required' => 'integer',
        'TargetType_Animal' => 'integer',
        'TargetType_Land' => 'integer',
        'TargetType_Building' => 'integer',
        'TargetGroup_Self' => 'integer',
        'TargetGroup_Ally' => 'integer',
        'TargetGroup_Party' => 'integer',
        'TargetGroup_Enemy_M' => 'integer',
        'TargetGroup_Enemy_P' => 'integer',
        'TargetGroup_Neutral' => 'integer',
        'TargetGroup_DontCare' => 'integer',
        'TargetEtc_SelectDeadBody' => 'integer',
        'ReqCommon_Mastery1' => 'integer',
        'ReqCommon_Mastery2' => 'integer',
        'ReqCommon_MasteryLevel1' => 'integer',
        'ReqCommon_MasteryLevel2' => 'integer',
        'ReqCommon_Str' => 'integer',
        'ReqCommon_Int' => 'integer',
        'ReqLearn_Skill1' => 'integer',
        'ReqLearn_Skill2' => 'integer',
        'ReqLearn_Skill3' => 'integer',
        'ReqLearn_SkillLevel1' => 'integer',
        'ReqLearn_SkillLevel2' => 'integer',
        'ReqLearn_SkillLevel3' => 'integer',
        'ReqLearn_SP' => 'integer',
        'ReqLearn_Race' => 'integer',
        'Req_Restriction1' => 'integer',
        'Req_Restriction2' => 'integer',
        'ReqCast_Weapon1' => 'integer',
        'ReqCast_Weapon2' => 'integer',
        'Consume_HP' => 'integer',
        'Consume_MP' => 'integer',
        'Consume_HPRatio' => 'integer',
        'Consume_MPRatio' => 'integer',
        'Consume_WHAN' => 'integer',
        'UI_SkillTab' => 'integer',
        'UI_SkillPage' => 'integer',
        'UI_SkillColumn' => 'integer',
        'UI_SkillRow' => 'integer',
        'AI_AttackChance' => 'integer',
        'AI_SkillType' => 'integer',
        'Param1' => 'integer',
        'Param2' => 'integer',
        'Param3' => 'integer',
        'Param4' => 'integer',
        'Param5' => 'integer',
        'Param6' => 'integer',
        'Param7' => 'integer',
        'Param8' => 'integer',
        'Param9' => 'integer',
        'Param10' => 'integer',
        'Param11' => 'integer',
        'Param12' => 'integer',
        'Param13' => 'integer',
        'Param14' => 'integer',
        'Param15' => 'integer',
        'Param16' => 'integer',
        'Param17' => 'integer',
        'Param18' => 'integer',
        'Param19' => 'integer',
        'Param20' => 'integer',
        'Param21' => 'integer',
        'Param22' => 'integer',
        'Param23' => 'integer',
        'Param24' => 'integer',
        'Param25' => 'integer',
        'Param26' => 'integer',
        'Param27' => 'integer',
        'Param28' => 'integer',
        'Param29' => 'integer',
        'Param30' => 'integer',
        'Param31' => 'integer',
        'Param32' => 'integer',
        'Param33' => 'integer',
        'Param34' => 'integer',
        'Param35' => 'integer',
        'Param36' => 'integer',
        'Param37' => 'integer',
        'Param38' => 'integer',
        'Param39' => 'integer',
        'Param40' => 'integer',
        'Param41' => 'integer',
        'Param42' => 'integer',
        'Param43' => 'integer',
        'Param44' => 'integer',
        'Param45' => 'integer',
        'Param46' => 'integer',
        'Param47' => 'integer',
        'Param48' => 'integer',
        'Param49' => 'integer',
        'Param50' => 'integer',
    ];
}
